### ISSUE TITLE
cell_read_count.py

### ISSUE THREAD

**Issue by 1092822678** [linjc16/DDS#1]
您好，preprocess中的cell_read_count.py好像缺失了

**Comment by Sleep226** [comment]
你好，我在运行训练部分第一条指令（bash dds/scripts/train_trans/run_dv_ppiv2_cons_tri.sh fold0 5e-5 0.01）时，报了这样一条错误：
  File "./dds/src/model/drug_transformer.py", line 14, in <module>
    from .trash.heads_prot_seq import BinaryClassProtSeqFrozenMLPHead
ModuleNotFoundError: No module named 'src.model.trash'
就是说在drug_transfomer.py文件运行时，第14行从.trash.heads_prot_seq import BinaryClassProtSeqFrozenMLPHead导入失败，我发现在model文件夹下缺失了文件.trash，能否麻烦您补充一下呢？

**Comment by linjc16** [comment]
ic. Please just delete this line and it may work then.
