### ISSUE TITLE
The file "cell_read_count.py" is missing.

### ISSUE THREAD

**Issue by Seana4rd** [linjc16/DDS#3]
Hi, thanks for your interesting work on drug coordination prediction, Pisces.
Inspired by your cell line characterization approach, I am attempting to reproduce this aspect of the work. Upon reviewing your Readme.txt, I noticed **the absence of the "cell_read_out.py" file.** **Could you please provide this file, or let me know if it is unnecessary for the actual process?_** 
I look forward to your prompt response. Thank you!

**Comment by linjc16** [comment]
Thanks for your feedback. Actually, "cell_read_out.py" was finally not used in this project. Sorry for the confusing README.md file, and I have reivised it.

**Comment by Seana4rd** [comment]
Thanks for your reply!
